<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptCompileOnSaveEnabled>false</TypeScriptCompileOnSaveEnabled>
  </PropertyGroup>
  <PropertyGroup>
    <!-- It's a mess. See https://github.com/dotnet/project-system/issues/3619 -->
    <RunWorkingDirectory>$(MSBuildProjectDirectory)</RunWorkingDirectory>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.AppIdentity.Hosting" Version="1.0.0--ci.2" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.Observable.ServerSample.App\CK.Observable.ServerSample.App.csproj" />
    <ProjectReference Include="..\CK.Observable.ServerSample.Builder\CK.Observable.ServerSample.Builder.csproj" ReferenceOutputAssembly="false" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>