<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.AspNet" Version="21.0.3" />
    <PackageReference Include="CK.Monitoring.Hosting" Version="26.0.3" />
    <PackageReference Include="CK.WeakAssemblyNameResolver" Version="0.5.2" />
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="All" />
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.Ng.ObservableDomain.WebSocket\CK.Ng.ObservableDomain.WebSocket.csproj" />
  </ItemGroup>
</Project>