nodeLinker: pnp

npmScopes:
  signature:
    npmAlwaysAuth: true
    npmAuthIdent: eWFybjpoY2hwaXI2dW1ta2Q3ZG1zdHNzbmdhbGE2cGhiM3E0MnZmenZlandwaWY2dnV3M3pncW9h
    npmRegistryServer: "https://invenietis.pkgs.visualstudio.com/_packaging/InternalNPM/npm/registry"
  signature-code:
    npmAlwaysAuth: true
    npmAuthIdent: eWFybjppb2Jzb2dobnlpc3JhcnhrcGtpdnpwYWY2dHVoaXJrMm5ycWFsbGF4YTJld2p5eHR1dnRx
    npmRegistryServer: "https://pkgs.dev.azure.com/Signature-Code/_packaging/Default/npm/registry"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
