<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.StObj.Model" Version="33.0.1--ci.1" />
    <PackageReference Include="CK.ActivityMonitor.SimpleSender" Version="26.0.1--ci.1" />
    <PackageReference Include="CK.PerfectEvent" Version="27.0.1--ci.1" />
    <PackageReference Include="System.Threading.Channels" Version="9.0.14" />
    <PackageReference Include="CK.BinarySerialization.Sliced" Version="13.0.1--ci.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="MSBuild/CK.Observable.Domain.targets">
      <Pack>true</Pack>
      <PackagePath>buildTransitive\CK.Observable.Domain.targets</PackagePath>
    </Content>
  </ItemGroup>
</Project>