<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.Ng.Cris.AspNet" Version="0.56.1" />
        <PackageReference Include="CK.Ng.AspNet.WebSocketChannel" Version="0.32.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CK.TS.ObservableDomain.DualCasing\CK.TS.ObservableDomain.DualCasing.csproj" />
      <ProjectReference Include="..\CK.Observable.WebSocketWatcher\CK.Observable.WebSocketWatcher.csproj" />
    </ItemGroup>

</Project>
