npmScopes:
  signature:
    npmRegistryServer: https://pkgs.dev.azure.com/Signature-OpenSource/Feeds/_packaging/NetCore3/npm/registry/
  signature-code:
    npmRegistryServer: https://pkgs.dev.azure.com/Signature-Code/_packaging/Default/npm/registry/
    npmAlwaysAuth: true
    npmAuthIdent: username:ZjVwcHJ6bGVvdWpvand2eWZwenhkYXlyZTdpZDNsdmdyZnhydXBmaWM1bW9rcjdvNjR3cQ==
