yarnPath: .yarn/releases/yarn-3.2.2.cjs

npmScopes:
  signature:
    npmRegistryServer: https://invenietis.pkgs.visualstudio.com/_packaging/InternalNPM/npm/registry
    npmAlwaysAuth: true
    npmAuthIdent: "eWFybjpoY2hwaXI2dW1ta2Q3ZG1zdHNzbmdhbGE2cGhiM3E0MnZmenZlandwaWY2dnV3M3pncW9h"
  signature-code:
    npmRegistryServer: https://pkgs.dev.azure.com/Signature-Code/_packaging/Default/npm/registry
    npmAlwaysAuth: true
    npmAuthIdent: "eWFybjppb2Jzb2dobnlpc3JhcnhrcGtpdnpwYWY2dHVoaXJrMm5ycWFsbGF4YTJld2p5eHR1dnRx"