<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CK.Observable.Domain\CK.Observable.Domain.csproj" />
      <ProjectReference Include="..\CK.TS.ObservableDomain\CK.TS.ObservableDomain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CK.Cris.Typescript" Version="1.0.0" />
        <PackageReference Include="CK.Cris.AspNet" Version="1.0.0" />
        <PackageReference Include="CK.AspNet.WebSocketChannel" Version="22.0.0" />
        <PackageReference Include="CK.TS.AspNet.WebSocketChannel" Version="1.0.0" />
    </ItemGroup>

</Project>
