<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CK.Observable.Domain\CK.Observable.Domain.csproj" />
      <ProjectReference Include="..\CK.TS.ObservableDomain\CK.TS.ObservableDomain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CK.Cris.Typescript" Version="0.55.3--ci.7" />
        <PackageReference Include="CK.Cris.AspNet" Version="0.55.3--ci.7" />
        <PackageReference Include="CK.AspNet.WebSocketChannel" Version="21.0.2--ci.7" />
        <PackageReference Include="CK.TS.AspNet.WebSocketChannel" Version="0.31.3--ci.19" />
    </ItemGroup>

</Project>
